---
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

# packer stores virtualbox version in this file
- name: Get VirtualBox version
  command: cat /home/{{ installation_os_user }}/.vbox_version
  register: cat_virtualbox_version_file
  when: virtualbox_version is not defined
  changed_when: false

- debug: var=cat_virtualbox_version_file

- name: set virtualbox from version_file
  set_fact:
    virtualbox_version: '{{ cat_virtualbox_version_file.stdout }}'
  when: not (cat_virtualbox_version_file.skipped is defined)

- debug: var=virtualbox_version

- name: Check if guest additions are installed
  shell: command -v VBoxClient --version >/dev/null 2>&1
  register: guest_additions_installed
  when: true
  ignore_errors: true
  changed_when: false

- debug: var=guest_additions_installed

- name: get guest additions version
  command: VBoxClient --version
  register: guest_additions_version
  when: guest_additions_installed.rc == 0
  changed_when: false

- debug: var=guest_additions_version

- debug:
    msg: "skipping installation, matching verion already installed"
  when:
    - guest_additions_version.stdout is defined
    - guest_additions_version.stdout is search(virtualbox_version)


- name: install guest guest additions
  block:
    - name: download guest additions iso
      get_url:
        url: "https://download.virtualbox.org/virtualbox/\
          {{ virtualbox_version }}/\
          VBoxGuestAdditions_{{ virtualbox_version }}.iso"
        dest: "/home/{{ installation_os_user }}/\
          VBoxGuestAdditions_{{ virtualbox_version }}.iso"

    - name: Create mountpoint for vbox guest additions iso
      file:
        path: /mnt/vbox
        state: directory

    - name: Mount VirtualBox guest additions ISO.
      mount:
        path: /mnt/vbox/
        src: "/home/{{ installation_os_user }}/\
          VBoxGuestAdditions_{{ virtualbox_version }}.iso"
        opts: loop,ro,noauto
        state: mounted
        fstype: iso9660

    - name: Run VirtualBox guest additions installation.
      command: '/mnt/vbox/VBoxLinuxAdditions.run --nox11'
      failed_when: false

    - name: Unmount VirtualBox guest additions ISO.
      mount:
        name: /mnt/vbox
        src: '/home/{{ installation_os_user }}/
          VBoxGuestAdditions_{{ virtualbox_version }}.iso'
        state: absent
        fstype: iso9660

    - name: Delete VirtualBox guest additions ISO.
      file:
        path: "/home/{{ installation_os_user }}/
          VBoxGuestAdditions_{{ virtualbox_version }}.iso"
        state: absent
  when:
    - not guest_additions_version.stdout is defined or
      not guest_additions_version.stdout is search(virtualbox_version)
