---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance-1
    box: geerlingguy/debian9
#   - name: instance-2
#     box: geerlingguy/centos7
provisioner:
  name: ansible
  log: true
scenario:
  name: default
verifier:
  name: goss
