---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: geerlingguy/debian9
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
