---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  # - name: instance-1
  #   box: geerlingguy/debian9
  - name: instance-2
    box: geerlingguy/centos7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  log: true
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
